# Generated by Django 5.0.6 on 2024-07-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_prodapp_alter_product_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
    ]
